// This file was autogenerated by ../../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../closure-thrones/thrones/ui/MenuButtonRenderer.js', ['thrones.ui.MenuButtonRenderer'], ['goog.ui.MenuButtonRenderer']);
